modLoader="javafml"
loaderVersion="[31,)"
#issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="modernity"
version="${file.jarVersion}"
displayName="The Modernity"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="examplemod.png"
credits="By RedGalaxy"
authors="RGSW"
description='''
The Modernity is a mod without a proper description, as this is still an in-development version.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
